### ISSUE TITLE
Shouldn't let the user create todo when they type nothing.

### ISSUE THREAD

**Issue by Chensokheng** [max-programming/max-todos#1]
@max-programming  When I try to use this app. I can add the todo item even tho I typed nothing. We should not let the user do that. I would like to work on that. Can I make a PR for this issue? 🙏

<img width="397" alt="Screen Shot 2020-10-07 at 7 17 06 PM" src="https://user-images.githubusercontent.com/52232579/95329822-c4ed3880-08d1-11eb-89b0-010c32b2957b.png">

**Comment by max-programming** [comment]
Yeah sure. That can fix this issue and make this app better. Go ahead!
