### ISSUE TITLE
Adding other social media links

### ISSUE THREAD

**Issue by m11dedhia** [max-programming/max-todos#11]
Along with the youtube link, you might also want to include other social media links

**Comment by max-programming** [comment]
There are many. Which ones do you recommend?

**Comment by m11dedhia** [comment]
Since i can see twitter, facebook and instagram on your youtube page, that will be a good start

**Comment by max-programming** [comment]
Oh wait, I thought it is another repo 🤦‍♂️. This thought came to my mind today itself. Thanks for the suggestion. I will add those.

**Comment by m11dedhia** [comment]
can i add it via the issue only? i will hyperlink them

**Comment by max-programming** [comment]
Yeah sure! But please make it style good so that it looks good on mobile

**Comment by m11dedhia** [comment]
thank you,
could you please assign it to me?

**Comment by m11dedhia** [comment]
Hey @max-programming  could you please add a ```hacktoberfest-accepted``` tag to this issue?
Thank you.

**Comment by max-programming** [comment]
No need for that. As it is merged, it is accepted by hacktoberfest

**Comment by m11dedhia** [comment]
hello @max-programming , sadly it is not directly considered for hacktoberfest until you add that tag to the merged repo. Could you please add it?

**Comment by max-programming** [comment]
I will add it. NP but, you can read this. If the PR is in a repo with `hacktoberfest` topic,and has been merged, it is counted
![image](https://user-images.githubusercontent.com/51731966/95943184-bab3c880-0e02-11eb-9eb4-16b3bfe1ab51.png)

**Comment by m11dedhia** [comment]
Thank you and sorry, I did not read it correctly
