### ISSUE TITLE
Fix long todo for mobile

### ISSUE THREAD

**Issue by max-programming** [max-programming/max-todos#16]
Any long todo looks bad on mobile. Something should be done to make it look good
![Screenshot_2020-10-20-14-31-39](https://user-images.githubusercontent.com/51731966/96565423-f73f6280-12e1-11eb-9b58-7b73ff6ed451.png)

**Comment by worachatsun** [comment]
Cloud you please check by PR
https://github.com/max-programming/max-todos/pull/18
