### ISSUE TITLE
Add Task Complete feature

### ISSUE THREAD

**Issue by m11dedhia** [max-programming/max-todos#40]
Add a task complete feature that allows the completed task to be striked out (either make a strikethrough or change the colour) and list it at the bottom.

**Comment by tusharkashyap63** [comment]
Can you be more clear? This already happens I guess.

**Comment by m11dedhia** [comment]
Yeah sorry, i did not try it out, it does make a strikethrough but it does not list it at the end so lets do that.

**Comment by tusharkashyap63** [comment]
Completed notes do go to the end of the list.

**Comment by max-programming** [comment]
> Yeah sorry, i did not try it out, it does make a strikethrough but it does not list it at the end so lets do that.

It goes to the end. I think It is not up to date on your end because it is a PWA so it caches everything. Try opening it in InPrivate or Incognito window. It'll work
