### ISSUE TITLE
Need a small user interface

### ISSUE THREAD

**Issue by lucas-jg** [max-programming/max-todos#44]
I prefer a small user interface, can I add it so that I can set the UI size?

**Comment by max-programming** [comment]
Didn't get about small UI, can you give an example?

**Comment by lucas-jg** [comment]
I'm sorry for the late reply.

I hope the text size would be smaller. And I hope the size of other components will be smaller to match the text size.

**Comment by max-programming** [comment]
> I'm sorry for the late reply.
> 
> I hope the text size would be smaller. And I hope the size of other components will be smaller to match the text size.

Yeah for mobile it's good to keep the text size small as more text won't fit easily. I'll try to work on it once my exams are over

**Comment by lucas-jg** [comment]
Please check the PR.
And can you release the latest version on netlify?

**Comment by max-programming** [comment]
> Please check the PR.
> And can you release the latest version on netlify?
> 
> I'm using max-todos well. Thank you.

Yep I checked the deploy preview [here](https://deploy-preview-45--maxtodos.netlify.app/)
