### ISSUE TITLE
Change color of starred todo text?

### ISSUE THREAD

**Issue by lucas-jg** [max-programming/max-todos#47]
I want to distinguish between starred todo.

```
if(todo.starred) {
      styles.text.color = isDark ? "#ffe066" : "#3f51b5"
}
```

![image](https://user-images.githubusercontent.com/31200025/102301096-85119400-3f99-11eb-868c-724579ec48ce.png)
![image](https://user-images.githubusercontent.com/31200025/102301121-9064bf80-3f99-11eb-9797-2f7b0d4f4b34.png)

**Comment by max-programming** [comment]
That will be another good improvement! Will you create a PR for that or should I assign it to myself?
