### ISSUE TITLE
Convert this to a TypeScript project?

### ISSUE THREAD

**Issue by max-programming** [max-programming/max-todos#50]
I am learning TypeScript and I love it so far. What do you think about converting this app to a TypeScript project?

@Steffan153 @worachatsun @m11dedhia @lucas-jg @tusharkashyap63 @Chensokheng @DharmarajX24

**Comment by johannchopin** [comment]
Yeah you should definitively do it 😉

**Comment by lucas-jg** [comment]
I love TypeScript
